# Generated by Django 5.2.13 on 2026-04-09 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('member_id', models.CharField(blank=True, db_index=True, help_text='Optional roster member id for cross-run coaching match.', max_length=32, null=True)),
                ('topic', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('failed', 'Failed')], db_index=True, default='running', max_length=32)),
                ('pipeline_snapshot', models.JSONField(default=list)),
                ('global_instructions_snapshot', models.TextField(blank=True)),
                ('ollama_base_url', models.CharField(blank=True, max_length=512)),
                ('ollama_model', models.CharField(blank=True, max_length=200)),
                ('timeout_sec', models.PositiveIntegerField(default=600)),
                ('final_report_text', models.TextField(blank=True)),
                ('report_draft_versions', models.JSONField(blank=True, help_text='Optional list of {step_index, preview} for debugging.', null=True)),
                ('chain_summary', models.TextField(blank=True, help_text='Crew kickoff raw result string when available.')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='actuarial_c_session_88ce95_idx'), models.Index(fields=['session_key', 'member_id', '-created_at'], name='actuarial_c_session_7f1bfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrewStepOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveSmallIntegerField()),
                ('step_kind', models.CharField(blank=True, max_length=32)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('ollama_model', models.CharField(blank=True, max_length=200)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='actuarial.crewrun')),
            ],
            options={
                'ordering': ['step_index'],
                'constraints': [models.UniqueConstraint(fields=('run', 'step_index'), name='uniq_crew_step_per_run_index')],
            },
        ),
    ]
