# Generated by Django 5.2.13 on 2026-04-09 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuarial', '0001_initial_crew_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewrun',
            name='dataset_summary_snapshot',
            field=models.TextField(blank=True, help_text='Full kickoff dataset summary (for background workers).'),
        ),
        migrations.CreateModel(
            name='CrewReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveSmallIntegerField()),
                ('step_kind', models.CharField(blank=True, max_length=32)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('report_body', models.TextField(blank=True)),
                ('source_raw', models.TextField(blank=True, help_text='Full model output for this step (optional).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_versions', to='actuarial.crewrun')),
            ],
            options={
                'ordering': ['step_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CrewRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_events', to='actuarial.crewrun')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='actuarial_c_run_id_d13f85_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='uniq_crew_run_event_seq')],
            },
        ),
    ]
