# Generated by Django 5.2.13 on 2026-04-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuarial', '0003_alter_crewrun_dataset_summary_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewrun',
            name='live_report_at',
            field=models.DateTimeField(blank=True, help_text='When live_report_text was last updated.', null=True),
        ),
        migrations.AddField(
            model_name='crewrun',
            name='live_report_text',
            field=models.TextField(blank=True, default='', help_text='Latest board-report draft during run (denormalized for fast polling).'),
        ),
    ]
