# Generated by Django 4.2.29 on 2026-04-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuarial', '0004_crewrun_live_report_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization profile',
                'verbose_name_plural': 'Organization profile',
            },
        ),
    ]
