# Generated by Django 4.2.29 on 2026-04-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuarial', '0005_organization_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewrun',
            name='approved_report_pdf',
            field=models.FileField(blank=True, help_text='Generated when the run is approved; stored under MEDIA_ROOT.', null=True, upload_to='crew_approved/%Y/%m/'),
        ),
    ]
