# Generated by Django 4.2.29 on 2026-04-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuarial', '0007_workspace_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewrun',
            name='session_key',
            field=models.CharField(db_index=True, help_text='Workspace scope key (fixed); not the Django browser session id.', max_length=64),
        ),
    ]
