# Generated by Django 4.2.29 on 2026-04-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuarial', '0008_alter_crewrun_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacestate',
            name='workspace_avatar_initials',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='workspacestate',
            name='workspace_department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workspacestate',
            name='workspace_display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workspacestate',
            name='workspace_email',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workspacestate',
            name='workspace_role',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
